create database QRSCS_Database

use QRSCS_Database
--USER TABLE

create table Users(
User_ID int not  null primary key identity,
Picture nvarchar(MAX),
Full_Name varchar (50) not  null,
Father_Name varchar(50) not  null,
NIC nvarchar(50) not  null,
Gender varchar(50) not  null,
DOB date not  null,
Contact_Number nvarchar(50) not  null,
Rank nvarchar(50),
Designation_Role varchar(50) not  null,
Address nvarchar(MAX) not  null,
City varchar(50)not  null,
State varchar(50)not  null,
UserName nvarchar(50)not  null,
Password nvarchar(50)not  null,
Creation_Date date,
Created_By varchar(50),
Update_Date date,
Updated_By varchar(50),
IsActive Bit
)
--NEW ADDMISS[dbo].[Case_History]ION TABLE

create table New_Admission (
GR_NO int not null primary key identity,
User_ID int not null foreign key references Users(User_ID),
Date_of_Addmission date not  null,
Student_First_Name  varchar(50) not  null,
Student_Last_Name  varchar(50) not  null,
Class int not  null,
Gender varchar(50) not  null,
Dob date not  null,
Place_of_Birth nvarchar(50) not  null,
Religion varchar(50) not  null,
Name_Last_School_Attended varchar(50),
Hobbies varchar(50),
Father_Name varchar(50) not  null,
Education varchar(50),
NIC nvarchar(50) not  null,
Relationship_with_Student varchar(50) not  null,
Monthly_Income nvarchar(50),
Occupation varchar(50),
Category varchar(30) not  null,
Address nvarchar(50) not  null,
City nvarchar(50) not  null,
State nvarchar(50) not  null,
Zip_Code nvarchar(10),
Contact nvarchar(50) not  null,
Phone_Residence nvarchar(50) not  null,
Phone_Office nvarchar(50),
Disability varchar(50) not  null,
Presenting_Complain nvarchar(50) not  null,
Update_Date date,
Updated_By varchar(50)
)

--CASE HISTORY TABLES
create table Case_History(
CaseHistory_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission(GR_NO),
Date_of_Examination date not null
)
create table Family_History(
Family_History_ID int not null primary key identity,
CaseHistory_ID int not null foreign key references Case_History(CaseHistory_ID),
Father_Name nvarchar(50) not null,
Father_Age int not null,
Father_Education nvarchar(50) ,
Father_Profession nvarchar(50) ,
Father_Financial_Status nvarchar(50) ,
Father_General_Health nvarchar(50) ,
Father_Blood_Group nvarchar(20) ,
Year_of_Marriage nvarchar(20) ,
Father_Age_at_the_time_of_Child_Birth int ,
Father_Paternal_Relationship nvarchar(50) ,
Father_Family_System nvarchar(50) ,
Mother_Name nvarchar(50),
Mother_Age int ,
Mother_Education nvarchar(50) ,
Mother_Profession nvarchar(50) ,
Mother_Financial_Status nvarchar(50) ,
Mother_General_Health nvarchar(50) ,
Mother_Blood_Group nvarchar(20) ,
Mother_Age_at_the_time_of_Child_Birth int ,
Mother_Paternal_Relationship nvarchar(50) ,
Mother_Family_System nvarchar(50) ,
)
create table Particulars_of_Sibling(
Particulars_of_Sibling_ID int not null primary key identity,
CaseHistory_ID int not null foreign key references Case_History(CaseHistory_ID),
Number_of_Siblings int not null,
Child_Order int ,
Any_Disability varchar(50)
)
create table Development_History(
Development_History_ID int not null primary key identity,
CaseHistory_ID int not null foreign key references Case_History(CaseHistory_ID),
Anemia varchar(10) not null,
Exposure_or_Radiation varchar(10) not null,
Rubella varchar(10) not null,
Attempted_Abortion varchar(10) not null,
Mediation_Drugs varchar(10) not null,
Alcohol varchar(10) not null,
Tobaco varchar(10) not null,
Any_Other_Development nvarchar(50),
Labor varchar(20) not null,
Condition_at_birth varchar(20) not null,
Attendant_During_Labour varchar(25) not null,
Juandice varchar(10) not null,
Convulsions varchar(10) not null,
Cyanotic_Attacks varchar(10) not null,
Feeding_Difficulty varchar(10) not null,
Any_Other_Neo_Natal_Period nvarchar(50) ,
)
create table Post_Natal(
Post_Natal_ID int not null primary key identity,
CaseHistory_ID int not null foreign key references Case_History(CaseHistory_ID),
Birth_Weight_Months nvarchar(20),
Smiling_Months nvarchar(20),
Cooing_Months nvarchar(20),
Neck_Control_Months nvarchar(20),
Teething_Months nvarchar(50),
Sitting_alone_Months nvarchar(20),
Crawling_Months nvarchar(20),
Walk_alone_Months nvarchar(20),
Spoke_1st_Word_Months nvarchar(20),
Able_to_Feed_alone_Months nvarchar(20),
Sphineter_Control_Months nvarchar(20),
Puberty_Months nvarchar(20),
Meningitis_Encephalitis_Months nvarchar(20),
Convulsion_Months nvarchar(20),
Head_Injury_Months nvarchar(20),
Dehydration_Months nvarchar(20),
Severe_Malnutrition_Months nvarchar(20),
Any_Other_illness_Months nvarchar(20),
Birth_Weight_Years nvarchar(20),
Smiling_Years nvarchar(20),
Cooing_Years nvarchar(20),
Neck_Control_Years nvarchar(20),
Teething_Years nvarchar(20) ,
Sitting_alone_Years nvarchar(20),
Crawling_Years nvarchar(20),
Walk_alone_Years nvarchar(20),
Spoke_1st_Word_Years nvarchar(50),
Able_to_Feed_alone_Years nvarchar(20),
Sphineter_Control_Years nvarchar(20),
Puberty_Years nvarchar(20),
Meningitis_Encephalitis_Years nvarchar(20),
Convulsion_Years nvarchar(20),
Head_Injury_Years nvarchar(20),
Dehydration_Years nvarchar(20),
Severe_Malnutrition_Years nvarchar(20), 
Any_Other_illness_Years nvarchar(50),
)
create table Medical_History(
Medical_History_ID int not null primary key identity,
CaseHistory_ID int not null foreign key references Case_History(CaseHistory_ID),
Measles_Answer varchar(10) not null,
Whooping_Enough_Answer varchar(10) not null,
Mumps_Answer varchar(10) not null,
Chickenpox_Answer varchar(10) not null,
Pneumonia_Answer varchar(10) not null,
Diphtheria_Answer varchar(10) not null,
Polio_Answer varchar(10) not null,
Influenza_Answer varchar(10) not null,
Typhoid_Answer varchar(10) not null,
Convulsion_Answer varchar(10) not null,
Rheumatic_Fever_Answer varchar(10) not null,
High_Grade_Fever_Answer varchar(10) not null,
Measles_Age int,
Whooping_Enough_Age int,
Mumps_Age int,
Chickenpox_Age int,
Pneumonia_Age int,
Diphtheria_Age int,
Polio_Age int,
Influenza_Age int,
Typhoid_Age int,
Convulsion_Age int,
Rheumatic_Fever_Age int,
High_Grade_Fever_Age int,
Any_Other nvarchar(50),
)
create table Education_History(
Education_History_ID int not null primary key identity,
CaseHistory_ID int not null foreign key references Case_History(CaseHistory_ID),
Name_of_School nvarchar(20),
Age_at_First_Admission nvarchar(20),
Performance nvarchar(20), 
Duration nvarchar(20), 
Reason_for_Withdrawal nvarchar(50)
)
create table Psycho_Social_Factors(
Psycho_Social_Factors_ID int not null primary key identity,
CaseHistory_ID int not null foreign key references Case_History(CaseHistory_ID),
Friends_Attitude nvarchar(20),
Sibling_Relationship nvarchar(20), 
HomeAndParent_Attitude nvarchar(30),
HobbiesAndInterest nvarchar(30)
)
create table Behavioral_Observation(
Behavioral_Observation_Answer_ID int not null primary key identity,
CaseHistory_ID int not null foreign key references Case_History(CaseHistory_ID),
Aggressive varchar(10) not null,
Restlessness varchar(10) not null,
Impulsivity varchar(10) not null,
Distractibility varchar(10) not null,
Destructive varchar(10) not null,
Hyper_Active varchar(10) not null,
Tantrum varchar(10) not null,
Self_Stimulation varchar(10) not null,
Shyness varchar(10) not null,
Complain varchar(10) not null,
Dependence varchar(10) not null,
Low_Self_Image varchar(10) not null,
Add_ varchar(10) not null,
Short_Attention_Span varchar(10) not null,
Poor_Motivation varchar(10) not null,
Isolation_ varchar(10) not null,
Withdrawn varchar(10) not null,
Asocial varchar(10) not null,
)
create table Conclusion(
Conclusion_ID int not null primary key identity,
CaseHistory_ID int not null foreign key references Case_History(CaseHistory_ID),
Conclusion_text varchar(100)
)
create table Recommendation(
Recommendation_Answer_ID int not null primary key identity,
CaseHistory_ID int not null foreign key references Case_History(CaseHistory_ID),
IEP varchar(10) not null,
Physical_Therapy varchar(10) not null,
Occupational_Therapy varchar(10) not null,
Speech_Therapy varchar(10) not null,
Music_Therapy varchar(10) not null,
Vocational_Therapy varchar(10) not null,
Correction_of_Defect varchar(10) not null,
Glasses varchar(10) not null,
Heraing_Aid varchar(10) not null,
Orthopedic_appliance varchar(10) not null,
Attention_to_home_situation varchar(10) not null,
Parental_Counseling varchar(10) not null,
Any_other_Home nvarchar(50) not null,
Home_Based_Program varchar(10) not null,
Special_School varchar(10) not null,
Medication varchar(10) not null,
Any_other nvarchar(50) ,
)

--SPEECH CASE HISTORY TABLES

create table Speach_Case_History(
Speach_Case_History_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission(GR_NO),
)
create table General_Information(
General_Information_ID int not null primary key identity,
Speach_Case_History_ID int not null foreign key references Speach_Case_History(Speach_Case_History_ID),
Today_Date date not null,
Child_Primary_Language nvarchar (Max) not  null,
Parent_Primary_Language nvarchar (Max) not  null,
Live_With_Both_Parents nvarchar (Max) not  null,
Child_Primary_Caregiver nvarchar (Max) not  null,
Child_Primary_Caregiver_Language nvarchar (Max) not  null,
)
create table Speach_and_Langauge(
Speach_and_Langauge_ID int not null primary key identity,
Speach_Case_History_ID int not null foreign key references Speach_Case_History(Speach_Case_History_ID),
Speech_Text nvarchar (Max) not  null
)
create table Receptive_langauge(
Receptive_langauge_ID int not null primary key identity,
Speach_Case_History_ID int not null foreign key references Speach_Case_History(Speach_Case_History_ID),
Single_Words nvarchar (50) not  null,
Yes_No_Questions nvarchar (50) not  null,
Sentences nvarchar (50) not  null,
WH_Questions nvarchar (50) not  null,
Routine_Questions nvarchar (50) not null,
Conversation_Text nvarchar (50) not null,
)
create table Expressive_Langauage(
Expressive_Langauage_ID int not null primary key identity,
Speach_Case_History_ID int not null foreign key references Speach_Case_History(Speach_Case_History_ID),
Babble nvarchar (50) not  null,
First_Word nvarchar (50) not  null,
Combine_2_Word nvarchar (50) not  null,
Complete_Sentence nvarchar (50) not  null,
Gestures nvarchar (50) not null,
Phrases nvarchar (50) not null,
Sing_Language nvarchar (50) not null,
Sentence nvarchar (50) not null,
Words nvarchar (50) not null,
Conversation_Ex_Text nvarchar (50) not null,
When_Did_Concerned_Child_Speech nvarchar (50) not null,
Caused_Your_Child_Difficulty nvarchar (50) not null,
Worse_Better_Overtime nvarchar (50) not null,
Self_Consious_Speech_Langauge nvarchar (50) not null,
Speech_Language_Hearing_Family nvarchar (50) not null,
Professionals_Seen_Child nvarchar (50) not null
)
create table Developmental_History(
Developmental_History_ID int not null primary key identity,
Speach_Case_History_ID int not null foreign key references Speach_Case_History(Speach_Case_History_ID),
Use_Single_Word nvarchar (50) not  null,
Combine_Word nvarchar (50) not  null,
Name_Single_Object nvarchar (50) not  null,
Use_Simple_Sentence nvarchar (50) not  null,
Engage_Conversation nvarchar (50) not null,
Consistently_Sound nvarchar (50) not null,
Difficulty_Hearing_Speech nvarchar (50) not null,
HearingTest_Where_When nvarchar (50) not null,
Diificult_Understand_Speech nvarchar (50) not null,
SpecificSounds_Incoorectly nvarchar (50) not null,
Difficulty_Understanding_Direction nvarchar (50) not null,
Difficulty_PlayActivities nvarchar (50) not null,
Engage_Excussive_Repetition_Word nvarchar (50) not null,
Feeding_Problem nvarchar (50) not null,
)

--SPEECH THERAPY TABLES

create table Speech_Therapy_Assessment(
Speech_Therapy_Assessment_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission(GR_NO),
Speech_Test_Image varchar (Max) not  null,
Date date not null,
)

--AUDIOLOGY ASSESSMENT

create table Audiology_Assessment (
Audiology_Assessment_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission(GR_NO),
Date_of_Assessment date not null,
Left_Ear_Air_UnmaskedFrequency nvarchar(MAX) null,
Left_Ear_Air_Unmasked_HearingLevel nvarchar(MAX)  null,
Left_Ear_Bone_MaskedFrequency nvarchar(MAX)  null,
Left_Ear_Bone_Masked_HearingLevel nvarchar(MAX)  null,
Right_Ear_Air_UnmaskedFrequency nvarchar(MAX)  null,
Right_Ear_Air_Unmasked_HearingLevel nvarchar(MAX)  null,
Right_Ear_Bone_MaskedFrequency nvarchar(MAX)  null,
Right_Ear_Bone_Masked_HearingLevel nvarchar(MAX) null,
Left_Ear_Mean nvarchar(max) null,
Right_Ear_Mean nvarchar(max) null,
);

--CREATE TEACHER TABLE

create table Create_Teacher(
Teacher_ID int not null primary key identity,
User_ID int not null foreign key references Users (User_ID) ,
Teacher_Picture varchar (Max) not null,
Teacher_Name nvarchar (50) not null,
Gender varchar(50) not  null,
NIC nvarchar(50) not  null,
Contact nvarchar(50) not  null,
Date_of_Birth date not null,
Email varchar (50) not null,
Address nvarchar(MAX) not  null,
City nvarchar(50) not  null,
State varchar(50) not null,
Status varchar (50) ,
Update_By varchar(50),
Update_Date date,
Creation_Date date
)

--OCCUPATIONAL THERAPY 1 TABLES

create table OccupationalTherapy1(
OT1_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission(GR_NO),
Date_of_Assessment date,
)
create table OT1_Page1(
Info_ID int not null primary key identity,
OT1_ID int not null foreign key references OccupationalTherapy1(OT1_ID),
Alertness nvarchar(Max),
Tone nvarchar(Max),
Reflexes nvarchar(Max),
Startle nvarchar(Max),
ATNR nvarchar(Max),
Gallant nvarchar(Max),
Landau nvarchar(Max),
Grasp nvarchar(Max),
Placing nvarchar(Max),
Parachute nvarchar(Max),
)
create table OT1_Page2(
Info_ID int not null primary key identity,
OT1_ID int not null foreign key references OccupationalTherapy1(OT1_ID),
Remark_3_Months nvarchar(Max),
Remark_6_Months nvarchar(Max),
Remark_7_Months nvarchar(Max),
Remark_6_To_7_Months nvarchar(Max),
Remark_8_To_10_Months nvarchar(Max),
Remark_10_To_11_Months_Crawl nvarchar(Max),
Remark_9_Months nvarchar(Max),
Remark_10_To_11_Months_Stands nvarchar(Max),
Remark_12_Months_Walks nvarchar(Max),
Remark_13_Months_Walks nvarchar(Max),
Remark_12_Months_Says nvarchar(Max),
Remark_15_To_18_Months_Joints nvarchar(Max),
Remark_13_Months_Feeds nvarchar(Max),
Remark_15_To_18_Months_Climb_Stairs nvarchar(Max),
Remark_2_To_3_Years nvarchar(Max),
Remark_3_To_4_Years nvarchar(Max),
)
create table OT1_Page3(
Info_ID int not null primary key identity,
OT1_ID int not null foreign key references OccupationalTherapy1(OT1_ID),
Reach nvarchar(Max),
Prehension nvarchar(Max),
Carry nvarchar(Max),
Release nvarchar(Max),
Isolated nvarchar(Max),
Opposition nvarchar(Max),
TiptoTip nvarchar(Max),
Finger nvarchar(Max),
Pre_writing nvarchar(Max),
Cognition nvarchar(Max),
Auditory nvarchar(Max),
Visual nvarchar(Max),
Taste_Smell nvarchar(Max),
Vestibular nvarchar(Max),
Praxis nvarchar(Max),
Stereignosis nvarchar(Max),
Communication nvarchar(Max),
Behaviour nvarchar(Max),
Sleep nvarchar(Max),
Activities nvarchar(Max),
)

---IEP TABLES---

create table IEPlan(
IEPlan_ID int not null primary key identity,
GR_No int not null foreign key references New_Admission(GR_No),
Date_Of_Assessment nvarchar,
)
create table MeetingInformation_IEP(
MeetingInformation_ID int not null primary key identity,
IEPlan_ID int not null foreign key references IEPlan(IEPlan_ID),
Initial_IEP bit,
Date_Initial_IEP date,
Annual_Review bit,
Date_Annual_Review date,
Review_Other_Than_Annaul_Review bit,
Date_Review_Other_Than_Annaul_Review date,
Ammendment bit,
Date_Ammendment date,
Communicating_Language nvarchar(50),
)
create table PresentLevel_IEP(
PresentLevel_ID int not null primary key identity,
IEPlan_ID int not null foreign key references IEPlan(IEPlan_ID),
Physical_Development nvarchar(50),
Communication nvarchar(50),
Self_Help_Skills nvarchar(50),
Cognition nvarchar(50),
Socialization nvarchar(50),
Functional_Academic nvarchar(50),
Academic_Performance nvarchar(50),
PreVocational_Skills nvarchar(50),
Others nvarchar(50),
)
create table SpecialInstructional_IEP(
SpecialInstruction_ID int not null primary key identity,
IEPlan_ID int not null foreign key references IEPlan(IEPlan_ID),
Question_1 nvarchar(50),
Question_2 nvarchar(50),
Question_3 nvarchar(50),
Question_4 nvarchar(50),
Question_5 nvarchar(50),
Question_6 nvarchar(50),
)
create table SupplementaryAids_IEP(
SupplementaryAids_ID int not null primary key identity,
IEPlan_ID int not null foreign key references IEPlan(IEPlan_ID),
Related_Services_1 nvarchar(50),
Related_Services_2 nvarchar(50),
Related_Services_3 nvarchar(50),
Related_Services_4 nvarchar(50),
Related_Services_5 nvarchar(50),
Related_Services_6 nvarchar(50),
Related_Services_7 nvarchar(50),
Provider_Name_1 nvarchar(50),
Provider_Name_2 nvarchar(50),
Provider_Name_3 nvarchar(50),
Provider_Name_4 nvarchar(50),
Provider_Name_5 nvarchar(50),
Provider_Name_6 nvarchar(50),
Provider_Name_7 nvarchar(50),
Hours_per_week_1 int,
Hours_per_week_2 int,
Hours_per_week_3 int,
Hours_per_week_4 int,
Hours_per_week_5 int,
Hours_per_week_6 int,
Hours_per_week_7 int,
Location_1 nvarchar(50),
Location_2 nvarchar(50),
Location_3 nvarchar(50),
Location_4 nvarchar(50),
Location_5 nvarchar(50),
Location_6 nvarchar(50),
Location_7 nvarchar(50),
Program_Modifications nvarchar(50) ,
Recommended_Instructional_Interventions nvarchar(max),
)
create table DevelopmentTeam_IEP(
DevelopmentTeam_ID int not null primary key identity,
IEPlan_ID int not null foreign key references IEPlan(IEPlan_ID),
DevelopmentTeam_Name_1 nvarchar(50),
DevelopmentTeam_Name_2 nvarchar(50),
DevelopmentTeam_Name_3 nvarchar(50),
DevelopmentTeam_Name_4 nvarchar(50),
DevelopmentTeam_Name_5 nvarchar(50),
DevelopmentTeam_Name_6 nvarchar(50),
DevelopmentTeam_Name_7 nvarchar(50),
--Team_Members_Signature nvarchar(50),
Position_1 nvarchar(50),
Position_2 nvarchar(50),
Position_3 nvarchar(50),
Position_4 nvarchar(50),
Position_5 nvarchar(50),
Position_6 nvarchar(50),
Position_7 nvarchar(50),
)

create table IEP_Page3(
IEP_Page3ID int not null primary key identity,
IEP_ID int not null foreign key references IEPlan(IEPlan_ID),
--Area_1 nvarchar(50) not null,
--Annual_Goal_1 nvarchar(50) not null,
Goal_1 nvarchar(50),
Goal_2 nvarchar(50),
Goal_3 nvarchar(50),
Goal_4 nvarchar(50),
Goal_5 nvarchar(50),
Goal_6 nvarchar(50),
Provider_1 varchar(50),
Provider_2 varchar(50),
Provider_3 varchar(50),
Provider_4 varchar(50),
Provider_5 varchar(50),
Provider_Others_1 nvarchar(50),
Evaluation_Method_1 nvarchar(50),
Evaluation_Method_2 nvarchar(50),
Evaluation_Method_3 nvarchar(50),
Evaluation_Method_4 nvarchar(50),
Evaluation_Method_5 nvarchar(50),
Evaluation_Method_Others_1 nvarchar(50),
Initial_Date_1 date,
Initial_Date_2 date,
Initial_Date_3 date,
Initial_Date_4 date,
Initial_Date_5 date,
Initial_Date_6 date,
Check_Date_1 date,
Check_Date_2 date,
Check_Date_3 date,
Check_Date_4 date,
Check_Date_5 date,
Check_Date_6 date,
Mastery_Date_1 date,
Mastery_Date_2 date,
Mastery_Date_3 date,
Mastery_Date_4 date,
Mastery_Date_5 date,
Mastery_Date_6 date,

--Area_2 nvarchar(50) not null,
--Annual_Goal_2 nvarchar(50) not null,
Goal_7 nvarchar(50),
Goal_8 nvarchar(50),
Goal_9 nvarchar(50),
Goal_10 nvarchar(50),
Goal_11 nvarchar(50),
Goal_12 nvarchar(50),
Provider_6 varchar(50),
Provider_7 varchar(50),
Provider_8 varchar(50),
Provider_9 varchar(50),
Provider_10 varchar(50),
Provider_Other_2 varchar(50),
Evaluation_Method_6 nvarchar(50),
Evaluation_Method_7 nvarchar(50),
Evaluation_Method_8 nvarchar(50),
Evaluation_Method_9 nvarchar(50),
Evaluation_Method_10 nvarchar(50),
Evaluation_Method_Others_2 nvarchar(50),
Initial_Date_7 date,
Initial_Date_8 date,
Initial_Date_9 date,
Initial_Date_10 date,
Initial_Date_11 date,
Initial_Date_12 date,
Check_Date_7 date,
Check_Date_8 date,
Check_Date_9 date,
Check_Date_10 date,
Check_Date_11 date,
Check_Date_12 date,
Mastery_Date_7 date,
Mastery_Date_8 date,
Mastery_Date_9 date,
Mastery_Date_10 date,
Mastery_Date_11 date,
Mastery_Date_12 date,
)

create table Physiotherapy(
PT_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission(GR_NO),
CP bit,
Down_Syndrome bit,
Autistic bit,
Muscular_Dystrophy bit,
Physical_Disability bit,
Others nvarchar (50),
Date_of_Assessment date ,
Siblings int,
Marriage_Type nvarchar(50),
Blood_Group nvarchar(50),
General_Health nvarchar(50),
Present_Complain nvarchar(200),
)
create table HistoryPregnancy_PT(
HistoryPregnancyPT_ID int not null primary key identity,
PT_ID int not null foreign key references Physiotherapy(PT_ID),
Pregnancy_Length nvarchar(50),
Pregnancy_Type nvarchar(50),
Birth_Detail nvarchar(50),
Breathing_Problem nvarchar(50),
Baby_Position nvarchar(50),
Pregnancy nvarchar(50),
)
create table MedicalInformation_PT(
MedicalInformationPT_ID int not null primary key identity,
PT_ID int not null foreign key references Physiotherapy(PT_ID),
Name_Of_Gp nvarchar(50),
Medication nvarchar(50),
Illness nvarchar(50),
Allergies nvarchar(50),
Tests nvarchar(50),
Surgical_Intervention nvarchar(50),
)
create table Milestone_PT(
MilestonePT_ID int not null primary key identity,
PT_ID int not null foreign key references Physiotherapy(PT_ID),
Cry nvarchar(50),
Neck_Control nvarchar(50),
Sitting nvarchar(50),
Crawling nvarchar(50),
Standing nvarchar(50),
Walking nvarchar(50),
Spoke_First_Word nvarchar(50),
Bowl_Bladder nvarchar(50),
Tactile nvarchar(50),
Auditory nvarchar(50),
Visual nvarchar(50),
Taste_Smell nvarchar(50),
)
create table PhysicalAssessment_PT(
PhysicalAssessmentPT_ID int not null primary key identity,
PT_ID int not null foreign key references Physiotherapy(PT_ID),
Contracture_Deformity nvarchar(50),
Muscle_Tone nvarchar(50),
UpperLimbs_Strength nvarchar(50),
UpperLimbs_Rom nvarchar(50),
LowerLimbs_Strength nvarchar(50),
LowerLimbs_Rom nvarchar(50),
)
create table TreatmentPlan_PT(
TreatmentPlanPT_ID int not null primary key identity,
PT_ID int not null foreign key references Physiotherapy(PT_ID),
LongTerm_Goal nvarchar(max),
ShortTerm_Goal nvarchar(max),
Recommendations nvarchar(max),
)
create table TestDone_PT(
TestDonePT_ID int not null primary key identity,
PT_ID int not null foreign key references Physiotherapy(PT_ID),
Ashworth nvarchar(50),
Goniometer nvarchar(50),
Muscle_Strength nvarchar(50),
)

--OCCUPATIONAL THERAPY 2 TABLES---

create table OccupationalTherapy2(
OT2_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission(GR_NO),
Test_Date date,
Examiner_Name nvarchar(50),
Examiner_Profession nvarchar(50),
Caregiver_Name nvarchar(50),
Caregiver_Relationship nvarchar(50),
Name_Of_School nvarchar(50),
School_Level int,
Child_Order nvarchar(50),
Children_Years_Living nvarchar(50),
)
create table AuditoryProcessing_OT2(
AuditoryProcessingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
AV_1 nvarchar(50),
AV_2 nvarchar(50),
SN_3 nvarchar(50),
SN_4 nvarchar(50),
AV_5 nvarchar(50),
SN_6 nvarchar(50),
SN_7 nvarchar(50),
RG_8 nvarchar(50),
Auditory_Raw_Score int,
Auditory_Comments nvarchar(max),
)
create table VisualProcessing_OT2(
VisualProcessingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
SN_9 nvarchar(50),
SN_10 nvarchar(50),
SN_11 nvarchar(50),
RG_12 nvarchar(50),
SN_13 nvarchar(50),
SK_14 nvarchar(50),
AV_15 nvarchar(50),
Visual_Raw_Score int,
Visual_Comments nvarchar(max),
)
create table TouchProcessing_OT2(
TouchProcessingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
SN_16 nvarchar(50),
SN_17 nvarchar(50),
AV_18 nvarchar(50),
SN_19 nvarchar(50),
SN_20 nvarchar(50),
SK_21 nvarchar(50),
SK_22 nvarchar(50),
RG_23 nvarchar(50),
RG_24 nvarchar(50),
SK_25 nvarchar(50),
RG_26 nvarchar(50),
Touch_Raw_Score int,
Touch_Comments nvarchar(max),
)
create table MovementProcessing_OT2(
MovementProcessingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
SK_27 nvarchar(50),
SK_28 nvarchar(50),
SK_29 nvarchar(50),
SK_30 nvarchar(50),
SK_31 nvarchar(50),
SK_32 nvarchar(50),
RG_33 nvarchar(50),
RG_34 nvarchar(50),
Movement_Raw_Score int,
Movement_Comments nvarchar(max),
)
create table BodyPositionProcessing_OT2(
BodyPositionProcessingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
RG_35 nvarchar(50),
RG_36 nvarchar(50),
RG_37 nvarchar(50),
RG_38 nvarchar(50),
RG_39 nvarchar(50),
RG_40 nvarchar(50),
SK_41 nvarchar(50),
SK_42 nvarchar(50),
Body_Postion_Raw_Score int,
Body_Position_Comments nvarchar(max),
)
create table OralSensoryProcessing_OT2(
OralSensoryProcessingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
Item_43 nvarchar(50),
SN_44 nvarchar(50),
SN_45 nvarchar(50),
SN_46 nvarchar(50),
SN_47 nvarchar(50),
SK_48 nvarchar(50),
SK_49 nvarchar(50),
SK_50 nvarchar(50),
SK_51 nvarchar(50),
SN_52 nvarchar(50),
Oral_Sensory_Raw_Score int,
Oral_Sensory_Comments nvarchar(max),
)
create table ConductProcessing_OT2(
ConductProcessingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
RG_53 nvarchar(50),
RG_54 nvarchar(50),
SK_55 nvarchar(50),
SK_56 nvarchar(50),
RG_57 nvarchar(50),
AV_58 nvarchar(50),
AV_59 nvarchar(50),
SK_60 nvarchar(50),
AV_61 nvarchar(50),
Conduct_Raw_Score int,
Conduct_Comments nvarchar(max),
)
create table SocialEmotionalProcessing_OT2(
SocialEmotionalProcessingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
RG_62 nvarchar(50),
AV_63 nvarchar(50),
AV_64 nvarchar(50),
AV_65 nvarchar(50),
AV_66 nvarchar(50),
AV_67 nvarchar(50),
AV_68 nvarchar(50),
SN_69 nvarchar(50),
AV_70 nvarchar(50),
AV_71 nvarchar(50),
AV_72 nvarchar(50),
SN_73 nvarchar(50),
AV_74 nvarchar(50),
AV_75 nvarchar(50),
Social_Emotional_Score int,
Social_Emotional_Comments nvarchar(max),
)
create table AttentionalProcessing_OT2(
AttentionalProcessingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
RG_76 nvarchar(50),
SN_77 nvarchar(50),
SN_78 nvarchar(50),
RG_79 nvarchar(50),
RG_80 nvarchar(50),
AV_81 nvarchar(50),
SK_82 nvarchar(50),
SK_83 nvarchar(50),
SN_84 nvarchar(50),
RG_85 nvarchar(50),
RG_86 nvarchar(50),
Attentional_Score int,
Attentional_Comments nvarchar(max),
)
create table Seeking_OT2(
SeekingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
Raw_Score_14 nvarchar(50),
Raw_Score_21 nvarchar(50),
Raw_Score_22 nvarchar(50),
Raw_Score_25 nvarchar(50),
Raw_Score_27 nvarchar(50),
Raw_Score_28 nvarchar(50),
Raw_Score_30 nvarchar(50),
Raw_Score_31 nvarchar(50),
Raw_Score_32 nvarchar(50),
Raw_Score_41 nvarchar(50),
Raw_Score_48 nvarchar(50),
Raw_Score_49 nvarchar(50),
Raw_Score_50 nvarchar(50),
Raw_Score_51 nvarchar(50),
Raw_Score_55 nvarchar(50),
Raw_Score_56 nvarchar(50),
Raw_Score_60 nvarchar(50),
Raw_Score_62 nvarchar(50),
Raw_Score_63 nvarchar(50),
Seeking_Score int,
)
create table Avoiding_OT2(
AvoidingOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
Raw_Score_1 nvarchar(50),
Raw_Score_2 nvarchar(50),
Raw_Score_5 nvarchar(50),
Raw_Score_15 nvarchar(50),
Raw_Score_18 nvarchar(50),
Raw_Score_58 nvarchar(50),
Raw_Score_59 nvarchar(50),
Raw_Score_61 nvarchar(50),
Raw_Score_63 nvarchar(50),
Raw_Score_64 nvarchar(50),
Raw_Score_65 nvarchar(50),
Raw_Score_66 nvarchar(50),
Raw_Score_67 nvarchar(50),
Raw_Score_68 nvarchar(50),
Raw_Score_70 nvarchar(50),
Raw_Score_71 nvarchar(50),
Raw_Score_72 nvarchar(50),
Raw_Score_74 nvarchar(50),
Raw_Score_75 nvarchar(50),
Raw_Score_81 nvarchar(50),
Avoiding_Score int,
)
create table Sensitivity_OT2(
SensitivityOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
Raw_Score_3 nvarchar(50),
Raw_Score_4 nvarchar(50),
Raw_Score_6 nvarchar(50),
Raw_Score_7 nvarchar(50),
Raw_Score_9 nvarchar(50),
Raw_Score_10 nvarchar(50),
Raw_Score_13 nvarchar(50),
Raw_Score_16 nvarchar(50),
Raw_Score_19 nvarchar(50),
Raw_Score_20 nvarchar(50),
Raw_Score_44 nvarchar(50),
Raw_Score_45 nvarchar(50),
Raw_Score_46 nvarchar(50),
Raw_Score_47 nvarchar(50),
Raw_Score_52 nvarchar(50),
Raw_Score_69 nvarchar(50),
Raw_Score_73 nvarchar(50),
Raw_Score_77 nvarchar(50),
Raw_Score_78 nvarchar(50),
Raw_Score_84 nvarchar(50),
Sensitivity_Score int,
)
create table Registration_OT2(
RegistrationOT2_ID int not null primary key identity,
OT2_ID int not null foreign key references OccupationalTherapy2(OT2_ID),
Raw_Score_8 nvarchar(50),
Raw_Score_12 nvarchar(50),
Raw_Score_23 nvarchar(50),
Raw_Score_24 nvarchar(50),
Raw_Score_26 nvarchar(50),
Raw_Score_33 nvarchar(50),
Raw_Score_34 nvarchar(50),
Raw_Score_35 nvarchar(50),
Raw_Score_36 nvarchar(50),
Raw_Score_37 nvarchar(50),
Raw_Score_38 nvarchar(50),
Raw_Score_39 nvarchar(50),
Raw_Score_40 nvarchar(50),
Raw_Score_53 nvarchar(50),
Raw_Score_54 nvarchar(50),
Raw_Score_57 nvarchar(50),
Raw_Score_62 nvarchar(50),
Raw_Score_76 nvarchar(50),
Raw_Score_79 nvarchar(50),
Raw_Score_80 nvarchar(50),
Raw_Score_85 nvarchar(50),
Raw_Score_86 nvarchar(50),
Registration_Score int,
)

--BEHAVIORAL THERAPY TABLES---
create table BehavioralTherapy(
BT_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission(GR_NO),
Date date not null
)
create table Week1_BT(
Week1BT_ID int not null primary key identity,
BT_ID int not null foreign key references BehavioralTherapy(BT_ID),
Throwing_Week1 nvarchar(50),
Pushing_Week1 nvarchar(50),
Pinching_Week1 nvarchar(50),
EyehandCoordination_Week1 nvarchar(50),
HeadacheComplain_Week1 nvarchar(50),
Vomiting_Week1 nvarchar(50),
AttachmentIssue_Week1 nvarchar(50),
Adjustment_Week1 nvarchar(50),
Biting_Week1 nvarchar(50),
HairPulling_Week1 nvarchar(50),
EatingProblems_Week1 nvarchar(50),
NoncomplianceBehavior_Week1 nvarchar(50),
Withdrawn_Week1 nvarchar(50),
Shyness_Week1 nvarchar(50),
Tolerance_Week1 nvarchar(50),
Irritability_Week1 nvarchar(50),
Unhappy_Week1 nvarchar(50),
Moodswings_Week1 nvarchar(50),
Hyperactive_Week1 nvarchar(50),
Isolation_Week1 nvarchar(50),
InAttention_Week1 nvarchar(50),
SustainAttention_Week1 nvarchar(50),
Restlessness_Week1 nvarchar(50),
AttentionSeeking_Week1 nvarchar(50),
Crying_Week1 nvarchar(50),
Shouting_Week1 nvarchar(50),
AbusiveLanguage_Week1 nvarchar(50),
Splitting_Week1 nvarchar(50),
SelfInjurious_Week1 nvarchar(50),
PhysicalAggression_Week1 nvarchar(50),
Other_Week1 nvarchar(50),
FrequencyBehavior_Week1 nvarchar(50)
)
create table Week2_BT(
Week2BT_ID int not null primary key identity,
BT_ID int not null foreign key references BehavioralTherapy(BT_ID),
Throwing_Week2 nvarchar(50),
Pushing_Week2 nvarchar(50),
Pinching_Week2 nvarchar(50),
EyehandCoordination_Week2 nvarchar(50),
HeadacheComplain_Week2 nvarchar(50),
Vomiting_Week2 nvarchar(50),
AttachmentIssue_Week2 nvarchar(50),
Adjustment_Week2 nvarchar(50),
Biting_Week2 nvarchar(50),
HairPulling_Week2 nvarchar(50),
EatingProblems_Week2 nvarchar(50),
NoncomplianceBehavior_Week2 nvarchar(50),
Withdrawn_Week2 nvarchar(50),
Shyness_Week2 nvarchar(50),
Tolerance_Week2 nvarchar(50),
Irritability_Week2 nvarchar(50),
Unhappy_Week2 nvarchar(50),
Moodswings_Week2 nvarchar(50),
Hyperactive_Week2 nvarchar(50),
Isolation_Week2 nvarchar(50),
InAttention_Week2 nvarchar(50),
SustainAttention_Week2 nvarchar(50),
Restlessness_Week2 nvarchar(50),
AttentionSeeking_Week2 nvarchar(50),
Crying_Week2 nvarchar(50),
Shouting_Week2 nvarchar(50),
AbusiveLanguage_Week2 nvarchar(50),
Splitting_Week2 nvarchar(50),
SelfInjurious_Week2 nvarchar(50),
PhysicalAggression_Week2 nvarchar(50),
Other_Week2 nvarchar(50),
FrequencyBehavior_Week2 nvarchar(50)
)
create table Week3_BT(
Week3BT_ID int not null primary key identity,
BT_ID int not null foreign key references BehavioralTherapy(BT_ID),
Throwing_Week3 nvarchar(50),
Pushing_Week3 nvarchar(50),
Pinching_Week3 nvarchar(50),
EyehandCoordination_Week3 nvarchar(50),
HeadacheComplain_Week3 nvarchar(50),
Vomiting_Week3 nvarchar(50),
AttachmentIssue_Week3 nvarchar(50),
Adjustment_Week3 nvarchar(50),
Biting_Week3 nvarchar(50),
HairPulling_Week3 nvarchar(50),
EatingProblems_Week3 nvarchar(50),
NoncomplianceBehavior_Week3 nvarchar(50),
Withdrawn_Week3 nvarchar(50),
Shyness_Week3 nvarchar(50),
Tolerance_Week3 nvarchar(50),
Irritability_Week3 nvarchar(50),
Unhappy_Week3 nvarchar(50),
Moodswings_Week3 nvarchar(50),
Hyperactive_Week3 nvarchar(50),
Isolation_Week3 nvarchar(50),
InAttention_Week3 nvarchar(50),
SustainAttention_Week3 nvarchar(50),
Restlessness_Week3 nvarchar(50),
AttentionSeeking_Week3 nvarchar(50),
Crying_Week3 nvarchar(50),
Shouting_Week3 nvarchar(50),
AbusiveLanguage_Week3 nvarchar(50),
Splitting_Week3 nvarchar(50),
SelfInjurious_Week3 nvarchar(50),
PhysicalAggression_Week3 nvarchar(50),
Other_Week3 nvarchar(50),
FrequencyBehavior_Week3 nvarchar(50)
)
create table Week4_BT(
Week4BT_ID int not null primary key identity,
BT_ID int not null foreign key references BehavioralTherapy(BT_ID),
Throwing_Week4 nvarchar(50),
Pushing_Week4 nvarchar(50),
Pinching_Week4 nvarchar(50),
EyehandCoordination_Week4 nvarchar(50),
HeadacheComplain_Week4 nvarchar(50),
Vomiting_Week4 nvarchar(50),
AttachmentIssue_Week4 nvarchar(50),
Adjustment_Week4 nvarchar(50),
Biting_Week4 nvarchar(50),
HairPulling_Week4 nvarchar(50),
EatingProblems_Week4 nvarchar(50),
NoncomplianceBehavior_Week4 nvarchar(50),
Withdrawn_Week4 nvarchar(50),
Shyness_Week4 nvarchar(50),
Tolerance_Week4 nvarchar(50),
Irritability_Week4 nvarchar(50),
Unhappy_Week4 nvarchar(50),
Moodswings_Week4 nvarchar(50),
Hyperactive_Week4 nvarchar(50),
Isolation_Week4 nvarchar(50),
InAttention_Week4 nvarchar(50),
SustainAttention_Week4 nvarchar(50),
Restlessness_Week4 nvarchar(50),
AttentionSeeking_Week4 nvarchar(50),
Crying_Week4 nvarchar(50),
Shouting_Week4 nvarchar(50),
AbusiveLanguage_Week4 nvarchar(50),
Splitting_Week4 nvarchar(50),
SelfInjurious_Week4 nvarchar(50),
PhysicalAggression_Week4 nvarchar(50),
Other_Week4 nvarchar(50),
FrequencyBehavior_Week4 nvarchar(50),
Solution nvarchar(50),
Remarks nvarchar(50),
Recommendation nvarchar(50),
)

--PSYCHOLOGICAL ASSESSMENT TABLES---

create table PsychologicalAssessment (
PA_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission(GR_NO),
Date date ,
Solosson_Intelligence_Test bit,
Draw_A_Person_Test bit, 
Colored_Progressive_Matrices bit, 
Standard_Progressive_Matrices bit, 
Vineland_Adaptive_Behavior_Scales bit, 
Childhood_Autism_Rating_Scale bit,
Attention_Deficit_Hyperactive_Disorder_Test bit,
Children_Apperception_Thematic_Test bit,
Personality_Assessment bit
)

--INTELLIGENCE QUOTIENT TABLES---
create table IntelligenceQuotient (
IQ_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission(GR_NO),
Date date ,
Communication bit,
Socialization bit,
Self_Help_Skills bit,
Cognition bit,
Physical_Development bit,
Communication_Score nvarchar(50),
Socialization_Score nvarchar(50),
Self_Help_Skills_Score nvarchar(50),
Cognition_Score nvarchar(50),
Physical_Development_Score nvarchar(50),
)

--RESULT TABLE

create table Result(
Result_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission (GR_NO) ,
Test_Type varchar (20) not null,
English int not null,
Urdu int not null,
Maths int not null,
Science int not null,
Social_Studies int not null,
Islamiat int not null,
Computer int not null,
Speech int not null,
[Language] int not null,
Concepts int not null,
Art_and_Drawing int not null,
Sindhi int not null,
Obtained_Total int not null,
Percentage int not null,
Grade varchar not null,
Result_Date date not null
)

--MIDTERM RESULT TABLE

create table MidTerm_Result(
MidTerm_Result_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission (GR_NO),
Term_Type varchar (20) not null,
English int not null,
Urdu int not null,
Maths int not null,
Science int not null,
Social_Studies int not null,
Islamiat int not null,
Computer int not null,
Speech int not null,
[Language] int not null,
Concepts int not null,
Art_and_Drawing int not null,
Sindhi int not null,
Obtained_Total int not null,
Percentage int not null,
Grade varchar not null,
Result_Date date not null,
Grand_English int  null,
Grand_Urdu int  null,
Grand_Maths int  null,
Grand_Science int  null,
Grand_Social_Studies int  null,
Grand_Islamiat int  null,
Grand_Computer int  null,
Grand_Speech int  null,
Grand_Language int  null,
Grand_Concepts int  null,
Grand_Art_and_Drawing int  null,
Grand_Sindhi int  null,
Grand_Total int  null,
Grand_Percentage int  null,
Grand_Grade varchar  null,
) 

create table Student_Current_Class(
Id int not null primary key identity,
GR_NO int foreign key references New_Admission (GR_NO),
Class int 
)

create table Student_Current_Status(
Id int not null primary key identity,
GR_NO int foreign key references New_Admission (GR_NO),
Class int,
Presentage varchar(MAX),
Result varchar(MAX),
Date varchar(20)
)
--IDD RESULT TABLE

create table IDD_Result(
IDD_Result_ID int not null primary key identity,
GR_NO int not null foreign key references New_Admission (GR_NO),
Term_Type varchar (20) not null,
English int not null,
Urdu int not null,
Maths int not null,
Computer_Studies int not null,
Islamiat int not null,
Social_Science int not null,
Conceptual int not null,
Speech int not null,
Art_and_Drawing int not null,
Music int not null,
Sports int not null,
Grade varchar not null,
Result_Date date not null,
lang_Speech_Communication int  null,
Gross_Motor_Development int  null,
Fine_Motor_Development int  null,
Socialization int  null,
Conceptual_Cognition int  null,
Daily_Living_Skills int  null,
Behavioral_Observation int  null,
Money_Management int  null,
Pre_Voc int  null,
Pre_Academic int  null,
GK int  null,
Computer int  null,
IEP_Music int  null,
IEP_Sports int  null,
IEP_Grade varchar  null,
IEP_Result_Date date not null,
Kitchen_Class int  null,
Home_Management int  null,
Self_Management int  null,
Art_Craft int  null,
Cognition_Conceptual int  null,
Islamiat_Nazra int  null,
VG_Music int  null,
VG_Sports int  null,
VG_Grade varchar  null,
VG_Result_Date date not null,
)

CREATE TABLE [dbo].[Student_Result_Status](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Class] [int] NULL,
	[GR_NO] [int] NULL,
	[Presentage] [varchar](max) NULL,
	[Result] [varchar](max) NULL,
	[Date] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

